-- AlterTable
ALTER TABLE "User" ADD COLUMN     "lastResetDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "tokensUsedToday" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "videosCreatedToday" INTEGER NOT NULL DEFAULT 0;
